### ISSUE TITLE
Add new access role to ThumbnailIconController

### ISSUE THREAD

**Issue by abdeje** [Geta/Epi.FontThumbnail#12]
We have an issue with the roles set on the controller, because some of our editors has limited access and none of the goups applied to day.

It would be nice to have an extra group like ThumbnailGroup, that you can use to set access rights with.
[Authorize(Roles = "Administrators, CmsAdmins, CmsEditors, WebAdmins, WebEditors, ThumbnailGroup")]

**Comment by degborta** [comment]
@abdeje Sorry for the late reply! I'll take a look and do something to handle this.

**Comment by degborta** [comment]
@abdeje Version 1.2.0 is uploaded to Episerver Nuget feed and should be available soon.
