### ISSUE TITLE
Some FA icons missing

### ISSUE THREAD

**Issue by gazab** [Geta/Epi.FontThumbnail#2]
I've noticed that some icons are missing. For example:

- newspaper-o
- question
- question-circle
- question-circle-o
- sticky-note
- sticky-note-o

I haven't had time to make a proper diff with the official list of icons but more are probably missing.

Thanks for a great plugin!

**Comment by degborta** [comment]
Thanks! Will have a look and see..

**Comment by degborta** [comment]
Updated enum with support for all fonts available in FA 4.7

Update should be available at Episerver nuget feed, version 1.0.4
