### ISSUE TITLE
update fontawesome to latest version

### ISSUE THREAD

**Issue by larswp** [Geta/Epi.FontThumbnail#4]
would it be possible to update the fontawesome font to latest version?

**Comment by johanbenschop** [comment]
I've just opened up a pull request #5 to support the latest Font Awesome version (5.3.0).

**Comment by degborta** [comment]
Sorry for the delay guys! Have been quite busy lately!

Thanks for the contribution @johanbenschop version 1.1.2 is uploaded to Episerver nuget feed and will hopefully be available in a day or so.

**Comment by johanbenschop** [comment]
Geta.Epi.FontThumbnail 1.1.2 has been released as of today.

To use the new Font Awesome 5 icons use the `FontAwesome5Brands`, `FontAwesome5Regular` and `FontAwesome5Solid` enums.

The enum for version 4 (`FontAwesome`) is still present and uses the older icons.
